# -*- coding: utf-8 -*-
"""codealpha3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJA2Q58afQeT7z2RV1VlxyLnOlKzTcOy
"""

import os
import shutil

source_folder = "images"
destination_folder = "jpg_files"

# Create destination folder if it does not exist
if not os.path.exists(destination_folder):
    os.mkdir(destination_folder)

# Move all JPG files
for file in os.listdir(source_folder):
    if file.lower().endswith(".jpg"):
        source = os.path.join(source_folder, file)
        destination = os.path.join(destination_folder, file)
        shutil.move(source, destination)

print("All JPG files moved successfully!")