# -*- coding: utf-8 -*-
"""codealpha2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfN7UVjwJ_J5BgUXm6dscrOeDF-md9Rz
"""

# Stock Portfolio Tracker

stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 140,
    "AMZN": 170,
    "MSFT": 420
}

total_investment = 0

print("Available Stocks:", ", ".join(stock_prices.keys()))

n = int(input("Enter number of stocks: "))

for i in range(n):
    stock = input("Enter stock name: ").upper()
    quantity = int(input("Enter quantity: "))

    if stock in stock_prices:
        value = stock_prices[stock] * quantity
        total_investment += value
        print(stock, "Value =", value)
    else:
        print("Stock not available.")

print("Total Investment =", total_investment)

# Save result in a text file
with open("portfolio.txt", "w") as file:
    file.write("Total Investment = " + str(total_investment))

print("Result saved in portfolio.txt")